class CreateSoms < ActiveRecord::Migration
  def change
    create_table :soms do |t|
      t.float :mil_percent
      t.float :wage
      t.float :me
      t.float :ome
      t.integer :off
      t.float :dme
      t.integer :def
      t.integer :gens_home
      t.integer :soldiers_home
      t.integer :ospecs_home
      t.integer :dspecs_home
      t.integer :elites_home
      t.integer :horses_home
      t.integer :gens_1
      t.integer :gens_2
      t.integer :gens_3
      t.integer :gens_4
      t.integer :gens_5
      t.integer :soilders_1
      t.integer :soldiers_2
      t.integer :soldiers_3
      t.integer :soldiers_4
      t.integer :soldiers_5
      t.integer :ospecs_1
      t.integer :ospecs_2
      t.integer :ospecs_3
      t.integer :ospecs_4
      t.integer :ospecs_5
      t.integer :dspecs_1
      t.integer :dspecs_2
      t.integer :dspecs_3
      t.integer :dspecs_4
      t.integer :dspecs_5
      t.integer :elites_1
      t.integer :elites_2
      t.integer :elites_3
      t.integer :elites_4
      t.integer :elites_5
      t.integer :horses_1
      t.integer :horses_2
      t.integer :horses_3
      t.integer :horses_4
      t.integer :horses_5
      t.integer :land_1
      t.integer :land_2
      t.integer :land_3
      t.integer :land_4
      t.integer :land_5
      t.integer :ospecs_training_1
      t.integer :ospecs_training_2
      t.integer :ospecs_training_3
      t.integer :ospecs_training_4
      t.integer :ospecs_training_5
      t.integer :ospecs_training_6
      t.integer :ospecs_training_7
      t.integer :ospecs_training_8
      t.integer :ospecs_training_9
      t.integer :ospecs_training_10
      t.integer :ospecs_training_11
      t.integer :ospecs_training_12
      t.integer :ospecs_training_13
      t.integer :ospecs_training_14
      t.integer :ospecs_training_15
      t.integer :ospecs_training_16
      t.integer :ospecs_training_17
      t.integer :ospecs_training_18
      t.integer :ospecs_training_19
      t.integer :ospecs_training_20
      t.integer :ospecs_training_21
      t.integer :ospecs_training_22
      t.integer :ospecs_training_23
      t.integer :ospecs_training_24
      t.integer :dspecs_training_1
      t.integer :dspecs_training_2
      t.integer :dspecs_training_3
      t.integer :dspecs_training_4
      t.integer :dspecs_training_5
      t.integer :dspecs_training_6
      t.integer :dspecs_training_7
      t.integer :dspecs_training_8
      t.integer :dspecs_training_9
      t.integer :dspecs_training_10
      t.integer :dspecs_training_11
      t.integer :dspecs_training_12
      t.integer :dspecs_training_13
      t.integer :dspecs_training_14
      t.integer :dspecs_training_15
      t.integer :dspecs_training_16
      t.integer :dspecs_training_17
      t.integer :dspecs_training_18
      t.integer :dspecs_training_19
      t.integer :dspecs_training_20
      t.integer :dspecs_training_21
      t.integer :dspecs_training_22
      t.integer :dspecs_training_23
      t.integer :dspecs_training_24
      t.integer :elites_training_1
      t.integer :elites_training_2
      t.integer :elites_training_3
      t.integer :elites_training_4
      t.integer :elites_training_5
      t.integer :elites_training_6
      t.integer :elites_training_7
      t.integer :elites_training_8
      t.integer :elites_training_9
      t.integer :elites_training_10
      t.integer :elites_training_11
      t.integer :elites_training_12
      t.integer :elites_training_13
      t.integer :elites_training_14
      t.integer :elites_training_15
      t.integer :elites_training_16
      t.integer :elites_training_17
      t.integer :elites_training_18
      t.integer :elites_training_19
      t.integer :elites_training_20
      t.integer :elites_training_21
      t.integer :elites_training_22
      t.integer :elites_training_23
      t.integer :elites_training_24
      t.integer :thieves_training_1
      t.integer :thieves_training_2
      t.integer :thieves_training_3
      t.integer :thieves_training_4
      t.integer :thieves_training_5
      t.integer :thieves_training_6
      t.integer :thieves_training_7
      t.integer :thieves_training_8
      t.integer :thieves_training_9
      t.integer :thieves_training_10
      t.integer :thieves_training_11
      t.integer :thieves_training_12
      t.integer :thieves_training_13
      t.integer :thieves_training_14
      t.integer :thieves_training_15
      t.integer :thieves_training_16
      t.integer :thieves_training_17
      t.integer :thieves_training_18
      t.integer :thieves_training_19
      t.integer :thieves_training_20
      t.integer :thieves_training_21
      t.integer :thieves_training_22
      t.integer :thieves_training_23
      t.integer :thieves_training_24

      t.timestamps
    end
  end
end
